name             'cerkberk2'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures cerkberk2'
long_description 'Installs/Configures cerkberk2'
version          '0.1.0'
